description: A function that returns pong to a ping over http
trigger:
    type: https
    method: GET
    paths:
        - /ping
includes:
    - /functions/pingpong.go
execution:
    timeout: 10s
    memory: 10MB
    call: ping
